#ifndef VKCODENAMES_H
#define VKCODENAMES_H

#include <map>
#include <vector>
#include <string>
#include <QString>

static std::vector<QString> vkCodenames = {
    "null",
    "LMB",
    "RMB",
    "CANCEL",
    "MMB",
    "X1MB",
    "X2MB",
    "undef",
    "Backspace",
    "Tab",
    "Reserved",
    "Reserved",
    "Clear",
    "Enter",
    "undef",
    "undef",
    "Shift",
    "Ctrl",
    "Alt",
    "Pause",
    "Caps Lock",
    "IME Kana/Hangul",
    "IME On",
    "IME Junja",
    "IME Final",
    "IME Kanji",
    "IME Off",
    "Escape",
    "IME Convert",
    "IME Nonconvrt",
    "IME Accept",
    "IME Mode Change Req",
    "Spacebar",
    "Page Up",
    "Page Down",
    "End",
    "Home",
    "Left Arrow",
    "Up Arrow",
    "Right Arrow",
    "Down Arrow",
    "Select",
    "Print",
    "Execute",
    "Print Screen",
    "Insert",
    "Delete",
    "Help",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "undef",
    "undef",
    "undef",
    "undef",
    "undef",
    "undef",
    "undef",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "Left Win",
    "Right Win",
    "Applications",
    "reserved",
    "Sleep",
    "Numpad 0",
    "Numpad 1",
    "Numpad 2",
    "Numpad 3",
    "Numpad 4",
    "Numpad 5",
    "Numpad 6",
    "Numpad 7",
    "Numpad 8",
    "Numpad 9",
    "Numpad Multiply",
    "Numpad Add",
    "Separator",
    "Numpad Subtract",
    "Numpad Decimal",
    "Numpad Divide",
    "F1",
    "F2",
    "F3",
    "F4",
    "F5",
    "F6",
    "F7",
    "F8",
    "F9",
    "F10",
    "F11",
    "F12",
    "F13",
    "F14",
    "F15",
    "F16",
    "F17",
    "F18",
    "F19",
    "F20",
    "F21",
    "F22",
    "F23",
    "F24",
    "unassigned",
    "unassigned",
    "unassigned",
    "unassigned",
    "unassigned",
    "unassigned",
    "unassigned",
    "unassigned",
    "Num Lock",
    "Scroll Lock",
    "OEM 1",
    "OEM 2",
    "OEM 3",
    "OEM 4",
    "OEM 5",
    "unassigned",
    "unassigned",
    "unassigned",
    "unassigned",
    "unassigned",
    "unassigned",
    "unassigned",
    "unassigned",
    "unassigned",
    "Left Shift",
    "Right Shift",
    "Left Ctrl",
    "Right Ctrl",
    "Left Alt",
    "Right Alt",
    "Browser Back",
    "Browser Forward",
    "Browser Refresh",
    "Browser Stop",
    "Browser Search",
    "Browser Favorites",
    "Browser Home",
    "Volume Mute",
    "Volume Down",
    "Volume Up",
    "Next Track",
    "Previous Track",
    "Stop Media",
    "Play/Pause Media",
    "Start Mail",
    "Select Media",
    "Start App1",
    "Start App2",
    "Reserved",
    "Reserved",
    ";",
    "=",
    ",",
    "-",
    ".",
    "/",
    "~",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "unassigned",
    "unassigned",
    "unassigned",
    "[",
    "\\",
    "]",
    "\'",
    "OEM 6",
    "Reserved",
    "OEM 7",
    "<>",
    "OEM 8",
    "OEM 9",
    "IME Process",
    "OEM 10",
    "Packet",
    "unassigned",
    "OEM 11",
    "OEM 12",
    "OEM 13",
    "OEM 14",
    "OEM 15",
    "OEM 16",
    "OEM 17",
    "OEM 18",
    "OEM 19",
    "OEM 20",
    "OEM 21",
    "OEM 22",
    "Attn",
    "CrSel",
    "ExSel",
    "Erase EOF",
    "Play",
    "Zoom",
    "Reserved",
    "PA1",
    "Clear"
};

/*static std::map<int, std::string> vkCodenames = {
    {1, "LMB"},
    {2, "RMB"},
    {3, "CANCEL"},
    {4, "MMB"},
    {5, "X1MB"},
    {6, "X2MB"},
    {7, "undef"},
    {8, "Backspace"},
    {9, "Tab"},
    {10, "Reserved"},
    {11, "Reserved"},
    {12, "Clear"},
    {13, "Enter"},
    {14, "undef"},
    {15, "undef"},
    {16, "Shift"},
    {17, "Ctrl"},
    {18, "Alt"},
    {19, "Pause"},
    {20, "Caps Lock"},
    {21, "IME Kana/Hangul"},
    {22, "IME On"},
    {23, "IME Junja"},
    {24, "IME Final"},
    {25, "IME Kanji"},
    {26, "IME Off"},
    {27, "Escape"},
    {28, "IME Convert"},
    {29, "IME Nonconvrt"},
    {30, "IME Accept"},
    {31, "IME Mode Change Req"},
    {32, "Spacebar"},
    {33, "Page Up"},
    {34, "Page Down"},
    {35, "End"},
    {36, "Home"},
    {37, "Left Arrow"},
    {38, "Up Arrow"},
    {39, "Right Arrow"},
    {40, "Down Arrow"},
    {41, "Select"},
    {42, "Print"},
    {43, "Execute"},
    {44, "Print Screen"},
    {45, "Insert"},
    {46, "Delete"},
    {47, "Help"},
    {48, "0"},
    {49, "1"},
    {50, "2"},
    {51, "3"},
    {52, "4"},
    {53, "5"},
    {54, "6"},
    {55, "7"},
    {56, "8"},
    {57, "9"},
    {58, "undef"},
    {59, "undef"},
    {60, "undef"},
    {61, "undef"},
    {62, "undef"},
    {63, "undef"},
    {64, "undef"},
    {65, "A"},
    {66, "B"},
    {67, "C"},
    {68, "D"},
    {69, "E"},
    {70, "F"},
    {71, "G"},
    {72, "H"},
    {73, "I"},
    {74, "J"},
    {75, "K"},
    {76, "L"},
    {77, "M"},
    {78, "N"},
    {79, "O"},
    {80, "P"},
    {81, "Q"},
    {82, "R"},
    {83, "S"},
    {84, "T"},
    {85, "U"},
    {86, "V"},
    {87, "W"},
    {88, "X"},
    {89, "Y"},
    {90, "Z"},
    {91, "Left Win"},
    {92, "Right Win"},
    {93, "Applications"},
    {94, "reserved"},
    {95, "Sleep"},
    {96, "Numpad 0"},
    {97, "Numpad 1"},
    {98, "Numpad 2"},
    {99, "Numpad 3"},
    {100, "Numpad 4"},
    {101, "Numpad 5"},
    {102, "Numpad 6"},
    {103, "Numpad 7"},
    {104, "Numpad 8"},
    {105, "Numpad 9"},
    {106, "Numpad Multiply"},
    {107, "Numpad Add"},
    {108, "Separator"},
    {109, "Numpad Subtract"},
    {110, "Numpad Decimal"},
    {111, "Numpad Divide"},
    {112, "F1"},
    {113, "F2"},
    {114, "F3"},
    {115, "F4"},
    {116, "F5"},
    {117, "F6"},
    {118, "F7"},
    {119, "F8"},
    {120, "F9"},
    {121, "F10"},
    {122, "F11"},
    {123, "F12"},
    {124, "F13"},
    {125, "F14"},
    {126, "F15"},
    {127, "F16"},
    {128, "F17"},
    {129, "F18"},
    {130, "F19"},
    {131, "F20"},
    {132, "F21"},
    {133, "F22"},
    {134, "F23"},
    {135, "F24"},
    {136, "unassigned"},
    {137, "unassigned"},
    {138, "unassigned"},
    {139, "unassigned"},
    {140, "unassigned"},
    {141, "unassigned"},
    {142, "unassigned"},
    {143, "unassigned"},
    {144, "Num Lock"},
    {145, "Scroll Lock"},
    {146, "OEM 1"},
    {147, "OEM 2"},
    {148, "OEM 3"},
    {149, "OEM 4"},
    {150, "OEM 5"},
    {151, "unassigned"},
    {152, "unassigned"},
    {153, "unassigned"},
    {154, "unassigned"},
    {155, "unassigned"},
    {156, "unassigned"},
    {157, "unassigned"},
    {158, "unassigned"},
    {159, "unassigned"},
    {160, "Left Shift"},
    {161, "Right Shift"},
    {162, "Left Ctrl"},
    {163, "Right Ctrl"},
    {164, "Left Alt"},
    {165, "Right Alt"},
    {166, "Browser Back"},
    {167, "Browser Forward"},
    {168, "Browser Refresh"},
    {169, "Browser Stop"},
    {170, "Browser Search"},
    {171, "Browser Favorites"},
    {172, "Browser Home"},
    {173, "Volume Mute"},
    {174, "Volume Down"},
    {175, "Volume Up"},
    {176, "Next Track"},
    {177, "Previous Track"},
    {178, "Stop Media"},
    {170, "Play/Pause Media"},
    {180, "Start Mail"},
    {181, "Select Media"},
    {182, "Start App1"},
    {183, "Start App2"},
    {184, "Reserved"},
    {185, "Reserved"},
    {186, ";"},
    {187, "="},
    {188, ","},
    {189, "-"},
    {190, "."},
    {191, "/"},
    {192, "~"},
    {193, "Reserved"},
    {194, "Reserved"},
    {195, "Reserved"},
    {196, "Reserved"},
    {197, "Reserved"},
    {198, "Reserved"},
    {199, "Reserved"},
    {200, "Reserved"},
    {201, "Reserved"},
    {202, "Reserved"},
    {203, "Reserved"},
    {204, "Reserved"},
    {205, "Reserved"},
    {206, "Reserved"},
    {207, "Reserved"},
    {208, "Reserved"},
    {209, "Reserved"},
    {210, "Reserved"},
    {211, "Reserved"},
    {212, "Reserved"},
    {213, "Reserved"},
    {214, "Reserved"},
    {215, "Reserved"},
    {216, "unassigned"},
    {217, "unassigned"},
    {218, "unassigned"},
    {219, "["},
    {220, "\\"},
    {221, "]"},
    {222, "\'"},
    {223, "OEM 6"},
    {224, "Reserved"},
    {225, "OEM 7"},
    {226, "<>"},
    {227, "OEM 8"},
    {228, "OEM 9"},
    {229, "IME Process"},
    {230, "OEM 10"},
    {231, "Packet"},
    {232, "unassigned"},
    {233, "OEM 11"},
    {234, "OEM 12"},
    {235, "OEM 13"},
    {237, "OEM 14"},
    {238, "OEM 15"},
    {239, "OEM 16"},
    {240, "OEM 17"},
    {241, "OEM 18"},
    {242, "OEM 19"},
    {243, "OEM 20"},
    {244, "OEM 21"},
    {245, "OEM 22"},
    {246, "Attn"},
    {247, "CrSel"},
    {248, "ExSel"},
    {249, "Erase EOF"},
    {250, "Play"},
    {251, "Zoom"},
    {252, "Reserved"},
    {253, "PA1"},
    {254, "Clear"}
};*/

#endif // VKCODENAMES_H
